### ISSUE TITLE
Interoperability issue between Sparrow Wallet and Stack Wallet

### ISSUE THREAD

**Issue by craigraw** [cypherstack/bip47#3]
I'm noticing an interoperability issue between Sparrow Wallet and Stack Wallet with regards to notification transactions. Specifically, a notification transaction created by Stack Wallet contains OP_RETURN data that does not compute to the sender payment code in Sparrow Wallet. 

I note that both projects are using the same test data in unit testing, so I'm not sure exactly where the difference lies. The method in Sparrow that calculates the sender payment code from a notification transaction can be found here: https://github.com/sparrowwallet/drongo/blob/d0da764aadfc9edc2a7fb35540eca0ee4c20ba0f/src/main/java/com/sparrowwallet/drongo/bip47/PaymentCode.java#L115

**Comment by julian-CStack** [comment]
This should have been fixed a little while back now
